import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const C = {
  materials: {
    mora: {name: 'Mora', icon: require('@/assets/material_icons/Mora.png')},
    experience: {name: "Hero's Wit", icon: require("@/assets/material_icons/Item_Hero_s_Wit.png")},
    crown: {name: 'Crown of Insight', icon: require('@/assets/material_icons/Crown_of_Insight.png')}, 
    water_crystal_T1: {name: 'Varunada Lazurite Sliver', icon: require('@/assets/material_icons/Varunada Lazurite Sliver.png')}, 
    water_crystal_T2: {name: 'Varunada Lazurite Fragment', icon: require('@/assets/material_icons/Varunada Lazurite Fragment.png')}, 
    water_crystal_T3: {name: 'Varunada Lazurite Chunk', icon: require('@/assets/material_icons/Varunada Lazurite Chunk.png')}, 
    water_crystal_T4: {name: 'Varunada Lazurite Gemstone', icon: require('@/assets/material_icons/Varunada Lazurite Gemstone.png')}, 
    ice_crystal_T1: {name: 'Shivada Jade Sliver', icon: require('@/assets/material_icons/Shivada Jade Sliver.png')}, 
    ice_crystal_T2: {name: 'Shivada Jade Fragment', icon: require('@/assets/material_icons/Shivada Jade Fragment.png')}, 
    ice_crystal_T3: {name: 'Shivada Jade Chunk', icon: require('@/assets/material_icons/Shivada Jade Chunk.png')}, 
    ice_crystal_T4: {name: 'Shivada Jade Gemstone', icon: require('@/assets/material_icons/Shivada Jade Gemstone.png')}, 
    anemo_crystal_T1: {name: 'Vayuda Turquoise Sliver', icon: require('@/assets/material_icons/Vayuda Turquoise Sliver.png')}, 
    anemo_crystal_T2: {name: 'Vayuda Turquoise Fragment', icon: require('@/assets/material_icons/Vayuda Turquoise Fragment.png')}, 
    anemo_crystal_T3: {name: 'Vayuda Turquoise Chunk', icon: require('@/assets/material_icons/Vayuda Turquoise Chunk.png')}, 
    anemo_crystal_T4: {name: 'Vayuda Turquoise Gemstone', icon: require('@/assets/material_icons/Vayuda Turquoise Gemstone.png')}, 
    electro_crystal_T1: {name: 'Vajrada Amethyst Sliver', icon: require('@/assets/material_icons/Vajrada Amethyst Sliver.png')}, 
    electro_crystal_T2: {name: 'Vajrada Amethyst Fragment', icon: require('@/assets/material_icons/Vajrada Amethyst Fragment.png')}, 
    electro_crystal_T3: {name: 'Vajrada Amethyst Chunk', icon: require('@/assets/material_icons/Vajrada Amethyst Chunk.png')}, 
    electro_crystal_T4: {name: 'Vajrada Amethyst Gemstone', icon: require('@/assets/material_icons/Vajrada Amethyst Gemstone.png')}, 
    geo_crystal_T1: {name: 'Prithiva Topaz Sliver', icon: require('@/assets/material_icons/Prithiva_Topaz_Sliver.png')}, 
    geo_crystal_T2: {name: 'Prithiva Topaz Fragment', icon: require('@/assets/material_icons/Prithiva_Topaz_Fragment.png')}, 
    geo_crystal_T3: {name: 'Prithiva Topaz Chunk', icon: require('@/assets/material_icons/Prithiva_Topaz_Chunk.png')}, 
    geo_crystal_T4: {name: 'Prithiva Topaz Gemstone', icon: require('@/assets/material_icons/Prithiva_Topaz_Gemstone.png')}, 
    book_prosperity_T1: {name: 'Teachings of Prosperity', icon: require('@/assets/material_icons/Item_Prosperity_Teachings.png')},
    book_prosperity_T2: {name: 'Guide to Prosperity', icon: require('@/assets/material_icons/Item_Prosperity_Guide.png')},
    book_prosperity_T3: {name: 'Philosophies of Prosperity', icon: require('@/assets/material_icons/Item_Prosperity_Philosophies.png')},
    book_gold_T1: {name: 'Teachings of Gold', icon: require('@/assets/material_icons/Item_Gold_Teachings.png')},
    book_gold_T2: {name: 'Guide to Gold', icon: require('@/assets/material_icons/Item_Gold_Guide.png')},
    book_gold_T3: {name: 'Philosophies of Gold', icon: require('@/assets/material_icons/Item_Gold_Philosophies.png')},
    book_dilligence_T1: {name: 'Teachings of Diligence', icon: require('@/assets/material_icons/Item_Diligence_Teachings.png')},
    book_dilligence_T2: {name: 'Guide to Diligence', icon: require('@/assets/material_icons/Item_Diligence_Guide.png')},
    book_dilligence_T3: {name: 'Philosophies of Diligence', icon: require('@/assets/material_icons/Item_Diligence_Philosophies.png')},
    book_ballad_T1: {name: 'Teachings of Ballad', icon: require('@/assets/material_icons/Item_Ballad_Teachings.png')},
    book_ballad_T2: {name: 'Guide to Ballad', icon: require('@/assets/material_icons/Item_Ballad_Guide.png')},
    book_ballad_T3: {name: 'Philosophies of Ballad', icon: require('@/assets/material_icons/Item_Ballad_Philosophies.png')},
    book_resistance_T1: {name: 'Teachings of Resistance', icon: require('@/assets/material_icons/Item_Resistance_Teachings.png')},
    book_resistance_T2: {name: 'Guide to Resistance', icon: require('@/assets/material_icons/Item_Resistance_Guide.png')},
    book_resistance_T3: {name: 'Philosophies of Resistance', icon: require('@/assets/material_icons/Item_Resistance_Philosophies.png')},
    book_freedom_T1: {name: 'Teachings of Freedom', icon: require('@/assets/material_icons/Item_Freedom_Teachings.png')},
    book_freedom_T2: {name: 'Guide to Freedom', icon: require('@/assets/material_icons/Item_Freedom_Guide.png')},
    book_freedom_T3: {name: 'Philosophies of Freedom', icon: require('@/assets/material_icons/Item_Freedom_Philosophies.png')},
    item_fatui_insignia_T1: {name: 'Recruit Insignia', icon: require('@/assets/material_icons/Item_Insignia_Recruit.png')}, 
    item_fatui_insignia_T2: {name: 'Sergeant Insignia', icon: require('@/assets/material_icons/Item_Insignia_Sergants.png')}, 
    item_fatui_insignia_T3: {name: 'Lieutnant Insignia', icon: require('@/assets/material_icons/Item_Insignia_Lieutenant.png')}, 
    item_raven_insignia_T1: {name: 'Treasure Hoarder Insignia', icon: require('@/assets/material_icons/Item_Raven_Insignia_Treasure.png')}, 
    item_raven_insignia_T2: {name: 'Silver Raven Insignia', icon: require('@/assets/material_icons/Item_Raven_Insignia_Silver.png')}, 
    item_raven_insignia_T3: {name: 'Golden Raven Insignia', icon: require('@/assets/material_icons/Item_Raven_Insignia_Gold.png')}, 
    item_scroll_T1: {name: 'Divining Scroll', icon: require('@/assets/material_icons/Item_Scroll_Divining.png')}, 
    item_scroll_T2: {name: 'Sealed Scroll', icon: require('@/assets/material_icons/Item_Scroll_Sealed.png')}, 
    item_scroll_T3: {name: 'Forbidden Curse Scroll', icon: require('@/assets/material_icons/Item_Scroll_Forbidden.png')}, 
    item_slime_T1: {name: 'Slime Condensate', icon: require('@/assets/material_icons/Item_Slime_Condensate.png')}, 
    item_slime_T2: {name: 'Slime Secretions', icon: require('@/assets/material_icons/Item_Slime_Secretions.png')}, 
    item_slime_T3: {name: 'Slime Concentrate', icon: require('@/assets/material_icons/Item_Slime_Concentrate.png')}, 
    item_mask_T1: {name: 'Damaged Mask', icon: require('@/assets/material_icons/Item_Mask_Damaged.png')}, 
    item_mask_T2: {name: 'Stained Mask', icon: require('@/assets/material_icons/Item_Mask_Stained.png')}, 
    item_mask_T3: {name: 'Ominous Mask', icon: require('@/assets/material_icons/Item_Mask_Ominous.png')}, 
    item_arrow_T1: {name: 'Firm Arrowhead', icon: require('@/assets/material_icons/Item_Arrowhead_Firm.png')}, 
    item_arrow_T2: {name: 'Sharp Arrowhead', icon: require('@/assets/material_icons/Item_Arrowhead_Sharp.png')}, 
    item_arrow_T3: {name: 'Weathered Arrowhead', icon: require('@/assets/material_icons/Item_Arrowhead_Weathered.png')}, 
    boss_ring_of_boreas: {name: 'Ring of Boreas', icon: require('@/assets/material_icons/Item_Boreas_Ring.png')}, 
    boss_dvalins_sigh: {name: "Dvalin’s Sigh", icon: require('@/assets/material_icons/Item_Dvalin_Sigh.png')}, 
    boss_dvalins_claw: {name: "Dvalin’s Claw", icon: require('@/assets/material_icons/Item_Dvalin_Claw.png')}, 
    boss_childe_shadow: {name: "Shadow of the Warrior", icon: require('@/assets/material_icons/Item_Childe_Shadow.png')},
    boss_childe_tusk: {name: "Tusk of Monoceros Caeli", icon: require('@/assets/material_icons/Item_Childe_Tusk.png')}, 
    boss_childe_shard: {name: "Shard of a Foul Legacy", icon: require('@/assets/material_icons/Item_Childe_Shard.png')}, 
    boss_boreas_tail: {name: "Tail of Boreas", icon: require('@/assets/material_icons/Item_Boreas_Tail.png')}, 
    boss_boreas_spirit: {name: "Tail of Boreas", icon: require('@/assets/material_icons/Item_Boreas_Spirit_Locket.png')}, 
    item_hoarfrost_core: {name: 'Hoarfrost Core', icon: require('@/assets/material_icons/Item_Hoarfrost_Core.png')}, 
    item_lightning_prism: {name: 'Lightning Prism', icon: require('@/assets/material_icons/Item_Lightning_Prism.png')}, 
    item_cleansing_heart: {name: 'Cleansing Heart', icon: require('@/assets/material_icons/Item_Cleansing_Heart.png')}, 
    item_basalt_pillar: {name: 'Basalt Pillar', icon: require('@/assets/material_icons/Item_Basalt_Pillar.png')}, 
    item_hurricane_seed: {name: 'Hurricane Seed', icon: require('@/assets/material_icons/Item_Hurricane_Seed.png')}, 
    speciality_valberry: {name: 'Valberry', icon: require('@/assets/material_icons/Item_Valberry.png')}, 
    speciality_noctilus_jade: {name: 'Noctilucous Jade', icon: require('@/assets/material_icons/Item_Noctilucous_Jade.png')},
    speciality_philanemo: {name: 'Philanemo Mushroom', icon: require('@/assets/material_icons/Item_Philanemo_Mushroom.png')},
    speciality_cecilia: {name: 'Cecilia', icon: require('@/assets/material_icons/Item_Cecilia.png')},
    speciality_silk_flower: {name: 'Slik Flower', icon: require('@/assets/material_icons/Item_Silk_Flower.png')},
    speciality_starconch: {name: 'Starconch', icon: require('@/assets/material_icons/Item_Starconch.png')},
    speciality_cor_lapis: {name: 'Cor Lapis', icon: require('@/assets/material_icons/Item_Cor_Lapis.png')},
    speciality_calla_lilly: {name: 'Calla Lily', icon: require('@/assets/material_icons/Item_Calla_Lily.png')},
    speciality_violetgrass: {name: 'Violetgrass', icon: require('@/assets/material_icons/Item_Violetgrass.png')},
    speciality_qingxin: {name: 'Qingxin', icon: require('@/assets/material_icons/Item_Qingxin.png')},
    speciality_lampgrass: {name: 'Small Lamp Grass', icon: require('@/assets/material_icons/Item_Small_Lamp_Grass.png')},
    speciality_wolfhook: {name: 'Wolfhook', icon: require('@/assets/material_icons/Item_Wolfhook.png')},
    speciality_glaze_lily: {name: 'Glaze Lily', icon: require('@/assets/material_icons/Item_Glaze_Lily.png')},
    item_nectar_T1: {name: 'Whopperflower Nectar', icon: require('@/assets/material_icons/Item_Nectar_Whopperflower.png')}, 
    item_nectar_T2: {name: 'Shimmering Nectar', icon: require('@/assets/material_icons/Item_Nectar_Shimmering.png')}, 
    item_nectar_T3: {name: 'Energy Nectar', icon: require('@/assets/material_icons/Item_Nectar_Energy.png')}
  }
}

export default new Vuex.Store({
  state: {
    count: 0, 
    xpAll: 0, 
    moraAll: 0,
    characters: [
      { 
        name: 'Zhongli', 
        picture: require('@/assets/character_portraits/zhongli.png'), 
        iconAtk: require('@/assets/talent_icons/rosaria_atk.png'), 
        iconSkill: require('@/assets/talent_icons/zhongli_skill.png'), 
        iconBurst: require('@/assets/talent_icons/zhongli_burst.png'),
        elementalMat_T1: C.materials.geo_crystal_T1,
        elementalMat_T2: C.materials.geo_crystal_T2, 
        elementalMat_T3: C.materials.geo_crystal_T3, 
        elementalMat_T4: C.materials.geo_crystal_T4, 
        core: C.materials.item_basalt_pillar,
        speciality: C.materials.speciality_cor_lapis, 
        commonMat_Ascension_T1: C.materials.item_slime_T1, 
        commonMat_Ascension_T2: C.materials.item_slime_T2, 
        commonMat_Ascension_T3: C.materials.item_slime_T3, 
        commonMat_Talent_T1: C.materials.item_slime_T1, 
        commonMat_Talent_T2: C.materials.item_slime_T2, 
        commonMat_Talent_T3: C.materials.item_slime_T3, 
        book_T1: C.materials.book_gold_T1, 
        book_T2: C.materials.book_gold_T2,
        book_T3: C.materials.book_gold_T3,
        worldBossMat: C.materials.boss_childe_tusk, 
        crown: C.materials.crown, 
        description: "Zhongli"
      }, 
      { 
        name: 'Noelle', 
        picture: require('@/assets/character_portraits/noelle.png'), 
        iconAtk: require('@/assets/talent_icons/greatsword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/noelle_skill.png'), 
        iconBurst: require('@/assets/talent_icons/noelle_burst.png'),
        elementalMat_T1: C.materials.geo_crystal_T1,
        elementalMat_T2: C.materials.geo_crystal_T2, 
        elementalMat_T3: C.materials.geo_crystal_T3, 
        elementalMat_T4: C.materials.geo_crystal_T4, 
        core: C.materials.item_basalt_pillar,
        speciality: C.materials.speciality_valberry, 
        commonMat_Ascension_T1: C.materials.item_mask_T1, 
        commonMat_Ascension_T2: C.materials.item_mask_T2, 
        commonMat_Ascension_T3: C.materials.item_mask_T3, 
        commonMat_Talent_T1: C.materials.item_mask_T1, 
        commonMat_Talent_T2: C.materials.item_mask_T2, 
        commonMat_Talent_T3: C.materials.item_mask_T3, 
        book_T1: C.materials.book_resistance_T1, 
        book_T2: C.materials.book_resistance_T2,
        book_T3: C.materials.book_resistance_T3,
        worldBossMat: C.materials.boss_dvalins_claw, 
        crown: C.materials.crown, 
        description: "Noelle"
      }, 
      { 
        name: 'Ningguang', 
        picture: require('@/assets/character_portraits/ningguang.png'), 
        iconAtk: require('@/assets/talent_icons/catalyst_atk.png'), 
        iconSkill: require('@/assets/talent_icons/ningguang_skill.png'), 
        iconBurst: require('@/assets/talent_icons/ningguang_burst.png'),
        elementalMat_T1: C.materials.geo_crystal_T1,
        elementalMat_T2: C.materials.geo_crystal_T2, 
        elementalMat_T3: C.materials.geo_crystal_T3, 
        elementalMat_T4: C.materials.geo_crystal_T4, 
        core: C.materials.item_basalt_pillar,
        speciality: C.materials.speciality_glaze_lily, 
        commonMat_Ascension_T1: C.materials.item_fatui_insignia_T1, 
        commonMat_Ascension_T2: C.materials.item_fatui_insignia_T2, 
        commonMat_Ascension_T3: C.materials.item_fatui_insignia_T3, 
        commonMat_Talent_T1: C.materials.item_fatui_insignia_T1, 
        commonMat_Talent_T2: C.materials.item_fatui_insignia_T2, 
        commonMat_Talent_T3: C.materials.item_fatui_insignia_T3, 
        book_T1: C.materials.book_prosperity_T1, 
        book_T2: C.materials.book_prosperity_T2,
        book_T3: C.materials.book_prosperity_T3,
        worldBossMat: C.materials.boss_boreas_spirit, 
        crown: C.materials.crown, 
        description: "Ningguang"
      }, 
      { 
        name: 'Razor', 
        picture: require('@/assets/character_portraits/razor.png'), 
        iconAtk: require('@/assets/talent_icons/greatsword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/razor_skill.png'), 
        iconBurst: require('@/assets/talent_icons/razor_burst.png'),
        elementalMat_T1: C.materials.electro_crystal_T1,
        elementalMat_T2: C.materials.electro_crystal_T2, 
        elementalMat_T3: C.materials.electro_crystal_T3, 
        elementalMat_T4: C.materials.electro_crystal_T4, 
        core: C.materials.item_lightning_prism,
        speciality: C.materials.speciality_wolfhook, 
        commonMat_Ascension_T1: C.materials.item_mask_T1, 
        commonMat_Ascension_T2: C.materials.item_mask_T2, 
        commonMat_Ascension_T3: C.materials.item_mask_T3, 
        commonMat_Talent_T1: C.materials.item_mask_T1, 
        commonMat_Talent_T2: C.materials.item_mask_T2, 
        commonMat_Talent_T3: C.materials.item_mask_T3, 
        book_T1: C.materials.book_resistance_T1, 
        book_T2: C.materials.book_resistance_T2,
        book_T3: C.materials.book_resistance_T3,
        worldBossMat: C.materials.boss_dvalins_claw, 
        crown: C.materials.crown, 
        description: "R A Z OMEGALUL R"
      }, 
      { 
        name: 'Lisa', 
        picture: require('@/assets/character_portraits/lisa.png'), 
        iconAtk: require('@/assets/talent_icons/catalyst_atk.png'), 
        iconSkill: require('@/assets/talent_icons/lisa_skill.png'), 
        iconBurst: require('@/assets/talent_icons/lisa_burst.png'),
        elementalMat_T1: C.materials.electro_crystal_T1,
        elementalMat_T2: C.materials.electro_crystal_T2, 
        elementalMat_T3: C.materials.electro_crystal_T3, 
        elementalMat_T4: C.materials.electro_crystal_T4, 
        core: C.materials.item_lightning_prism,
        speciality: C.materials.speciality_valberry, 
        commonMat_Ascension_T1: C.materials.item_slime_T1, 
        commonMat_Ascension_T2: C.materials.item_slime_T2, 
        commonMat_Ascension_T3: C.materials.item_slime_T3, 
        commonMat_Talent_T1: C.materials.item_slime_T1, 
        commonMat_Talent_T2: C.materials.item_slime_T2, 
        commonMat_Talent_T3: C.materials.item_slime_T3, 
        book_T1: C.materials.book_ballad_T1, 
        book_T2: C.materials.book_ballad_T2,
        book_T3: C.materials.book_ballad_T3,
        worldBossMat: C.materials.boss_dvalins_claw, 
        crown: C.materials.crown, 
        description: "Lisa"
      }, 
      { 
        name: 'Keqing', 
        picture: require('@/assets/character_portraits/keqing.png'), 
        iconAtk: require('@/assets/talent_icons/sword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/keqing_skill.png'), 
        iconBurst: require('@/assets/talent_icons/keqing_burst.png'),
        elementalMat_T1: C.materials.electro_crystal_T1,
        elementalMat_T2: C.materials.electro_crystal_T2, 
        elementalMat_T3: C.materials.electro_crystal_T3, 
        elementalMat_T4: C.materials.electro_crystal_T4, 
        core: C.materials.item_lightning_prism,
        speciality: C.materials.speciality_cor_lapis, 
        commonMat_Ascension_T1: C.materials.item_nectar_T1, 
        commonMat_Ascension_T2: C.materials.item_nectar_T2, 
        commonMat_Ascension_T3: C.materials.item_nectar_T3, 
        commonMat_Talent_T1: C.materials.item_nectar_T1, 
        commonMat_Talent_T2: C.materials.item_nectar_T2, 
        commonMat_Talent_T3: C.materials.item_nectar_T3, 
        book_T1: C.materials.book_prosperity_T1, 
        book_T2: C.materials.book_prosperity_T2,
        book_T3: C.materials.book_prosperity_T3,
        worldBossMat: C.materials.boss_ring_of_boreas, 
        crown: C.materials.crown, 
        description: "Keqing"
      }, 
      { 
        name: 'Fischl', 
        picture: require('@/assets/character_portraits/fischl.png'), 
        iconAtk: require('@/assets/talent_icons/bow_atk.png'), 
        iconSkill: require('@/assets/talent_icons/fischl_skill.png'), 
        iconBurst: require('@/assets/talent_icons/fischl_burst.png'),
        elementalMat_T1: C.materials.electro_crystal_T1,
        elementalMat_T2: C.materials.electro_crystal_T2, 
        elementalMat_T3: C.materials.electro_crystal_T3, 
        elementalMat_T4: C.materials.electro_crystal_T4, 
        core: C.materials.item_lightning_prism,
        speciality: C.materials.speciality_lampgrass, 
        commonMat_Ascension_T1: C.materials.item_arrow_T1, 
        commonMat_Ascension_T2: C.materials.item_arrow_T2, 
        commonMat_Ascension_T3: C.materials.item_arrow_T3, 
        commonMat_Talent_T1: C.materials.item_arrow_T1, 
        commonMat_Talent_T2: C.materials.item_arrow_T2, 
        commonMat_Talent_T3: C.materials.item_arrow_T3, 
        book_T1: C.materials.book_ballad_T1, 
        book_T2: C.materials.book_ballad_T2,
        book_T3: C.materials.book_ballad_T3,
        worldBossMat: C.materials.boss_boreas_spirit, 
        crown: C.materials.crown, 
        description: "Fischl"
      }, 
      { 
        name: 'Ganyu', 
        picture: require('@/assets/character_portraits/ganyu.png'), 
        iconAtk: require('@/assets/talent_icons/bow_atk.png'), 
        iconSkill: require('@/assets/talent_icons/ganyu_skill.png'), 
        iconBurst: require('@/assets/talent_icons/ganyu_burst.png'),
        elementalMat_T1: C.materials.ice_crystal_T1, 
        elementalMat_T2: C.materials.ice_crystal_T2, 
        elementalMat_T3: C.materials.ice_crystal_T3, 
        elementalMat_T4: C.materials.ice_crystal_T4, 
        core: C.materials.item_hoarfrost_core,
        speciality: C.materials.speciality_qingxin, 
        commonMat_Ascension_T1: C.materials.item_nectar_T1, 
        commonMat_Ascension_T2: C.materials.item_nectar_T2, 
        commonMat_Ascension_T3: C.materials.item_nectar_T3, 
        commonMat_Talent_T1: C.materials.item_nectar_T1, 
        commonMat_Talent_T2: C.materials.item_nectar_T2, 
        commonMat_Talent_T3: C.materials.item_nectar_T3, 
        book_T1: C.materials.book_dilligence_T1,
        book_T2: C.materials.book_dilligence_T2,
        book_T3: C.materials.book_dilligence_T3,
        worldBossMat: C.materials.boss_childe_shadow, 
        crown: C.materials.crown, 
        description: "Ganyu"
      }, 
      { 
        name: 'Diona', 
        picture: require('@/assets/character_portraits/diona.png'), 
        iconAtk: require('@/assets/talent_icons/bow_atk.png'), 
        iconSkill: require('@/assets/talent_icons/diona_skill.png'), 
        iconBurst: require('@/assets/talent_icons/diona_burst.png'),
        elementalMat_T1: C.materials.ice_crystal_T1, 
        elementalMat_T2: C.materials.ice_crystal_T2, 
        elementalMat_T3: C.materials.ice_crystal_T3, 
        elementalMat_T4: C.materials.ice_crystal_T4, 
        core: C.materials.item_hoarfrost_core,
        speciality: C.materials.speciality_calla_lilly, 
        commonMat_Ascension_T1: C.materials.item_arrow_T1, 
        commonMat_Ascension_T2: C.materials.item_arrow_T2, 
        commonMat_Ascension_T3: C.materials.item_arrow_T3, 
        commonMat_Talent_T1: C.materials.item_arrow_T1, 
        commonMat_Talent_T2: C.materials.item_arrow_T2, 
        commonMat_Talent_T3: C.materials.item_arrow_T3, 
        book_T1: C.materials.book_freedom_T1,
        book_T2: C.materials.book_freedom_T2,
        book_T3: C.materials.book_freedom_T3,
        worldBossMat: C.materials.boss_childe_shard, 
        crown: C.materials.crown, 
        description: "Diona"
      }, 
      { 
        name: 'Qiqi', 
        picture: require('@/assets/character_portraits/qiqi.png'), 
        iconAtk: require('@/assets/talent_icons/sword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/qiqi_skill.png'), 
        iconBurst: require('@/assets/talent_icons/qiqi_burst.png'),
        elementalMat_T1: C.materials.ice_crystal_T1, 
        elementalMat_T2: C.materials.ice_crystal_T2, 
        elementalMat_T3: C.materials.ice_crystal_T3, 
        elementalMat_T4: C.materials.ice_crystal_T4, 
        core: C.materials.item_hoarfrost_core,
        speciality: C.materials.speciality_violetgrass, 
        commonMat_Ascension_T1: C.materials.item_scroll_T1, 
        commonMat_Ascension_T2: C.materials.item_scroll_T2, 
        commonMat_Ascension_T3: C.materials.item_scroll_T3, 
        commonMat_Talent_T1: C.materials.item_scroll_T1, 
        commonMat_Talent_T2: C.materials.item_scroll_T2, 
        commonMat_Talent_T3: C.materials.item_scroll_T3, 
        book_T1: C.materials.book_prosperity_T1,
        book_T2: C.materials.book_prosperity_T2,
        book_T3: C.materials.book_prosperity_T3,
        worldBossMat: C.materials.boss_boreas_tail, 
        crown: C.materials.crown, 
        description: "Qiqi"
      }, 
      { 
        name: 'Kaeya', 
        picture: require('@/assets/character_portraits/kaeya.png'), 
        iconAtk: require('@/assets/talent_icons/sword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/kaeya_skill.png'), 
        iconBurst: require('@/assets/talent_icons/kaeya_burst.png'),
        elementalMat_T1: C.materials.ice_crystal_T1, 
        elementalMat_T2: C.materials.ice_crystal_T2, 
        elementalMat_T3: C.materials.ice_crystal_T3, 
        elementalMat_T4: C.materials.ice_crystal_T4, 
        core: C.materials.item_hoarfrost_core,
        speciality: C.materials.speciality_calla_lilly, 
        commonMat_Ascension_T1: C.materials.item_raven_insignia_T1, 
        commonMat_Ascension_T2: C.materials.item_raven_insignia_T2, 
        commonMat_Ascension_T3: C.materials.item_raven_insignia_T3, 
        commonMat_Talent_T1: C.materials.item_raven_insignia_T1, 
        commonMat_Talent_T2: C.materials.item_raven_insignia_T2, 
        commonMat_Talent_T3: C.materials.item_raven_insignia_T3, 
        book_T1: C.materials.book_ballad_T1,
        book_T2: C.materials.book_ballad_T2,
        book_T3: C.materials.book_ballad_T3,
        worldBossMat: C.materials.boss_boreas_spirit, 
        crown: C.materials.crown, 
        description: "Kaeya"
      }, 
      { 
        name: 'Chongyun', 
        picture: require('@/assets/character_portraits/chongyun.png'), 
        iconAtk: require('@/assets/talent_icons/greatsword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/chongyun_skill.png'), 
        iconBurst: require('@/assets/talent_icons/chongyun_burst.png'),
        elementalMat_T1: C.materials.ice_crystal_T1, 
        elementalMat_T2: C.materials.ice_crystal_T2, 
        elementalMat_T3: C.materials.ice_crystal_T3, 
        elementalMat_T4: C.materials.ice_crystal_T4, 
        core: C.materials.item_hoarfrost_core,
        speciality: C.materials.speciality_cor_lapis, 
        commonMat_Ascension_T1: C.materials.item_mask_T1, 
        commonMat_Ascension_T2: C.materials.item_mask_T2, 
        commonMat_Ascension_T3: C.materials.item_mask_T3, 
        commonMat_Talent_T1: C.materials.item_mask_T1, 
        commonMat_Talent_T2: C.materials.item_mask_T2, 
        commonMat_Talent_T3: C.materials.item_mask_T3, 
        book_T1: C.materials.book_dilligence_T1,
        book_T2: C.materials.book_dilligence_T2,
        book_T3: C.materials.book_dilligence_T3,
        worldBossMat: C.materials.boss_dvalins_sigh, 
        crown: C.materials.crown, 
        description: "Chongyun"
      }, 
      { 
        name: 'Tartgalia', 
        picture: require('@/assets/character_portraits/childe.png'), 
        iconAtk: require('@/assets/talent_icons/bow_atk.png'), 
        iconSkill: require('@/assets/talent_icons/childe_skill.png'), 
        iconBurst: require('@/assets/talent_icons/childe_burst.png'),
        elementalMat_T1: C.materials.water_crystal_T1,
        elementalMat_T2: C.materials.water_crystal_T2, 
        elementalMat_T3: C.materials.water_crystal_T3, 
        elementalMat_T4: C.materials.water_crystal_T4, 
        core: C.materials.item_cleansing_heart,
        speciality: C.materials.speciality_starconch, 
        commonMat_Ascension_T1: C.materials.item_fatui_insignia_T1, 
        commonMat_Ascension_T2: C.materials.item_fatui_insignia_T2, 
        commonMat_Ascension_T3: C.materials.item_fatui_insignia_T3, 
        commonMat_Talent_T1: C.materials.item_fatui_insignia_T1, 
        commonMat_Talent_T2: C.materials.item_fatui_insignia_T2, 
        commonMat_Talent_T3: C.materials.item_fatui_insignia_T3, 
        book_T1: C.materials.book_freedom_T1, 
        book_T2: C.materials.book_freedom_T2,
        book_T3: C.materials.book_freedom_T3,
        worldBossMat: C.materials.boss_childe_shard, 
        crown: C.materials.crown, 
        description: "Tartgalia"
      },
      { 
        name: 'Rosaria', 
        picture: require('@/assets/character_portraits/rosaria.png'), 
        iconAtk: require('@/assets/talent_icons/rosaria_atk.png'), 
        iconSkill: require('@/assets/talent_icons/rosaria_skill.png'), 
        iconBurst: require('@/assets/talent_icons/rosaria_burst.png'),
        elementalMat_T1: C.materials.ice_crystal_T1, 
        elementalMat_T2: C.materials.ice_crystal_T2, 
        elementalMat_T3: C.materials.ice_crystal_T3, 
        elementalMat_T4: C.materials.ice_crystal_T4, 
        core: C.materials.item_hoarfrost_core,
        speciality: C.materials.speciality_valberry, 
        commonMat_Ascension_T1: C.materials.item_fatui_insignia_T1, 
        commonMat_Ascension_T2: C.materials.item_fatui_insignia_T2, 
        commonMat_Ascension_T3: C.materials.item_fatui_insignia_T3, 
        commonMat_Talent_T1: C.materials.item_fatui_insignia_T1, 
        commonMat_Talent_T2: C.materials.item_fatui_insignia_T2, 
        commonMat_Talent_T3: C.materials.item_fatui_insignia_T3, 
        book_T1: C.materials.book_ballad_T1,
        book_T2: C.materials.book_ballad_T2,
        book_T3: C.materials.book_ballad_T3,
        worldBossMat: C.materials.boss_childe_shadow, 
        crown: C.materials.crown, 
        description: "MILKY MILKY WARM AND TASTY! MOMMY! MILKY! PLEASE BE HASTY! REFRESHING DRINK FROM MOMMY’S UDDERS! I WANT MOMMY’S AND NO OTHER’S! GIVE IT! GIVE IT! GIVE IT NOW! GIVE ME MILKY, LAZY SOW! UNTIL YOU DO I’LL SCREAM I’LL SHOUT! I’LL CRY I’LL WHINE AND STOMP ABOUT! UNTIL MY BELLY IS FULL AND HAPPY! I REFUSE TO TAKE A NAPPY!"
      }, 
      { 
        name: 'Beidou', 
        picture: require('@/assets/character_portraits/beidou.png'), 
        iconAtk: require('@/assets/talent_icons/beidou_atk.png'), 
        iconSkill: require('@/assets/talent_icons/beidou_skill.png'), 
        iconBurst: require('@/assets/talent_icons/beidou_burst.png'),
        elementalMat_T1: C.materials.electro_crystal_T1,
        elementalMat_T2: C.materials.electro_crystal_T2, 
        elementalMat_T3: C.materials.electro_crystal_T3, 
        elementalMat_T4: C.materials.electro_crystal_T4, 
        core: C.materials.item_lightning_prism,
        speciality: C.materials.speciality_noctilus_jade, 
        commonMat_Ascension_T1: C.materials.item_raven_insignia_T1, 
        commonMat_Ascension_T2: C.materials.item_raven_insignia_T2, 
        commonMat_Ascension_T3: C.materials.item_raven_insignia_T3, 
        commonMat_Talent_T1: C.materials.item_raven_insignia_T1, 
        commonMat_Talent_T2: C.materials.item_raven_insignia_T2, 
        commonMat_Talent_T3: C.materials.item_raven_insignia_T3, 
        book_T1: C.materials.book_gold_T1, 
        book_T2: C.materials.book_gold_T2,
        book_T3: C.materials.book_gold_T3,
        worldBossMat: C.materials.boss_dvalins_sigh, 
        crown: C.materials.crown, 
        description: "Beidou"
      }, 
      { 
        name: 'Mona', 
        picture: require('@/assets/character_portraits/mona.png'), 
        iconAtk: require('@/assets/talent_icons/mona_atk.png'), 
        iconSkill: require('@/assets/talent_icons/mona_skill.png'), 
        iconBurst: require('@/assets/talent_icons/mona_burst.png'),
        elementalMat_T1: C.materials.water_crystal_T1,
        elementalMat_T2: C.materials.water_crystal_T2, 
        elementalMat_T3: C.materials.water_crystal_T3, 
        elementalMat_T4: C.materials.water_crystal_T4, 
        core: C.materials.item_cleansing_heart,
        speciality: C.materials.speciality_philanemo, 
        commonMat_Ascension_T1: C.materials.item_nectar_T1, 
        commonMat_Ascension_T2: C.materials.item_nectar_T2, 
        commonMat_Ascension_T3: C.materials.item_nectar_T3, 
        commonMat_Talent_T1: C.materials.item_nectar_T1, 
        commonMat_Talent_T2: C.materials.item_nectar_T2, 
        commonMat_Talent_T3: C.materials.item_nectar_T3, 
        book_T1: C.materials.book_resistance_T1, 
        book_T2: C.materials.book_resistance_T2,
        book_T3: C.materials.book_resistance_T3,
        worldBossMat: C.materials.boss_ring_of_boreas, 
        crown: C.materials.crown, 
        description: "Mona"
      }, 
      { 
        name: 'Albedo', 
        picture: require('@/assets/character_portraits/albedo.png'), 
        iconAtk: require('@/assets/talent_icons/sword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/albedo_skill.png'), 
        iconBurst: require('@/assets/talent_icons/albedo_burst.png'),
        elementalMat_T1: C.materials.geo_crystal_T1,
        elementalMat_T2: C.materials.geo_crystal_T2, 
        elementalMat_T3: C.materials.geo_crystal_T3, 
        elementalMat_T4: C.materials.geo_crystal_T4, 
        core: C.materials.item_basalt_pillar,
        speciality: C.materials.speciality_cecilia, 
        commonMat_Ascension_T1: C.materials.item_scroll_T1, 
        commonMat_Ascension_T2: C.materials.item_scroll_T2, 
        commonMat_Ascension_T3: C.materials.item_scroll_T3, 
        commonMat_Talent_T1: C.materials.item_scroll_T1, 
        commonMat_Talent_T2: C.materials.item_scroll_T2, 
        commonMat_Talent_T3: C.materials.item_scroll_T3, 
        book_T1: C.materials.book_ballad_T1, 
        book_T2: C.materials.book_ballad_T2,
        book_T3: C.materials.book_ballad_T3,
        worldBossMat: C.materials.boss_childe_tusk, 
        crown: C.materials.crown, 
        description: "Albedo"
      }, 
      { 
        name: 'Venti', 
        picture: require('@/assets/character_portraits/venti.png'), 
        iconAtk: require('@/assets/talent_icons/bow_atk.png'), 
        iconSkill: require('@/assets/talent_icons/venti_skill.png'), 
        iconBurst: require('@/assets/talent_icons/venti_burst.png'),
        elementalMat_T1: C.materials.anemo_crystal_T1,
        elementalMat_T2: C.materials.anemo_crystal_T2, 
        elementalMat_T3: C.materials.anemo_crystal_T3, 
        elementalMat_T4: C.materials.anemo_crystal_T4, 
        core: C.materials.item_hurricane_seed,
        speciality: C.materials.speciality_cecilia, 
        commonMat_Ascension_T1: C.materials.item_slime_T1, 
        commonMat_Ascension_T2: C.materials.item_slime_T2, 
        commonMat_Ascension_T3: C.materials.item_slime_T3, 
        commonMat_Talent_T1: C.materials.item_slime_T1, 
        commonMat_Talent_T2: C.materials.item_slime_T2, 
        commonMat_Talent_T3: C.materials.item_slime_T3, 
        book_T1: C.materials.book_ballad_T1, 
        book_T2: C.materials.book_ballad_T2,
        book_T3: C.materials.book_ballad_T3,
        worldBossMat: C.materials.boss_boreas_tail, 
        crown: C.materials.crown, 
        description: "Imagine not having Venti"
      }, 
      { 
        name: 'Barbara', 
        picture: require('@/assets/character_portraits/barbara.png'), 
        iconAtk: require('@/assets/talent_icons/catalyst_atk.png'), 
        iconSkill: require('@/assets/talent_icons/barbara_skill.png'), 
        iconBurst: require('@/assets/talent_icons/barbara_burst.png'),
        elementalMat_T1: C.materials.water_crystal_T1,
        elementalMat_T2: C.materials.water_crystal_T2, 
        elementalMat_T3: C.materials.water_crystal_T3, 
        elementalMat_T4: C.materials.water_crystal_T4, 
        core: C.materials.item_cleansing_heart,
        speciality: C.materials.speciality_philanemo, 
        commonMat_Ascension_T1: C.materials.item_scroll_T1, 
        commonMat_Ascension_T2: C.materials.item_scroll_T2, 
        commonMat_Ascension_T3: C.materials.item_scroll_T3, 
        commonMat_Talent_T1: C.materials.item_scroll_T1, 
        commonMat_Talent_T2: C.materials.item_scroll_T2, 
        commonMat_Talent_T3: C.materials.item_scroll_T3, 
        book_T1: C.materials.book_freedom_T1, 
        book_T2: C.materials.book_freedom_T2,
        book_T3: C.materials.book_freedom_T3,
        worldBossMat: C.materials.boss_ring_of_boreas, 
        crown: C.materials.crown, 
        description: "Barbara"
      }, 
      { 
        name: 'Xingqiu', 
        picture: require('@/assets/character_portraits/xinqui.png'), 
        iconAtk: require('@/assets/talent_icons/sword_atk.png'), 
        iconSkill: require('@/assets/talent_icons/xinqui_skill.png'), 
        iconBurst: require('@/assets/talent_icons/xinqui_burst.png'),
        elementalMat_T1: C.materials.water_crystal_T1,
        elementalMat_T2: C.materials.water_crystal_T2, 
        elementalMat_T3: C.materials.water_crystal_T3, 
        elementalMat_T4: C.materials.water_crystal_T4, 
        core: C.materials.item_cleansing_heart,
        speciality: C.materials.speciality_silk_flower, 
        commonMat_Ascension_T1: C.materials.item_mask_T1, 
        commonMat_Ascension_T2: C.materials.item_mask_T2, 
        commonMat_Ascension_T3: C.materials.item_mask_T3, 
        commonMat_Talent_T1: C.materials.item_mask_T1, 
        commonMat_Talent_T2: C.materials.item_mask_T2, 
        commonMat_Talent_T3: C.materials.item_mask_T3, 
        book_T1: C.materials.book_gold_T1, 
        book_T2: C.materials.book_gold_T2,
        book_T3: C.materials.book_gold_T3,
        worldBossMat: C.materials.boss_boreas_tail, 
        crown: C.materials.crown, 
        description: "Xingqiu"
      }
    ],
    xpTable: [
      {xp: 120175, mora: 24000},
      {xp: 578325, mora: 115600}, 
      {xp: 579100, mora: 115800},
      {xp: 854125, mora: 170800},
      {xp: 1195925, mora: 239000},
      {xp: 1611875, mora: 322200},
      {xp: 3424125, mora: 684600}
    ], 
    ascensionTable: [
      {elementalMat_T1: 1, elementalMat_T2: 0, elementalMat_T3: 0, elementalMat_T4: 0, core: 0, speciality: 3, commonMat_Ascension_T1: 3, commonMat_Ascension_T2: 0, commonMat_Ascension_T3: 0, mora: 20000}, 
      {elementalMat_T1: 0, elementalMat_T2: 3, elementalMat_T3: 0, elementalMat_T4: 0, core: 2, speciality: 10, commonMat_Ascension_T1: 15, commonMat_Ascension_T2: 0, commonMat_Ascension_T3: 0, mora: 40000}, 
      {elementalMat_T1: 0, elementalMat_T2: 6, elementalMat_T3: 0, elementalMat_T4: 0, core: 4, speciality: 20, commonMat_Ascension_T1: 0, commonMat_Ascension_T2: 12, commonMat_Ascension_T3: 0, mora: 60000}, 
      {elementalMat_T1: 0, elementalMat_T2: 0, elementalMat_T3: 3, elementalMat_T4: 0, core: 8, speciality: 30, commonMat_Ascension_T1: 0, commonMat_Ascension_T2: 18, commonMat_Ascension_T3: 0, mora: 80000},
      {elementalMat_T1: 0, elementalMat_T2: 0, elementalMat_T3: 6, elementalMat_T4: 0, core: 12, speciality: 45, commonMat_Ascension_T1: 0, commonMat_Ascension_T2: 0, commonMat_Ascension_T3: 16, mora: 100000},
      {elementalMat_T1: 0, elementalMat_T2: 0, elementalMat_T3: 0, elementalMat_T4: 6, core: 20, speciality: 60, commonMat_Ascension_T1: 0, commonMat_Ascension_T2: 0, commonMat_Ascension_T3: 24, mora: 120000}  
    ], 
    talentTable: [
      {book_T1: 3, book_T2: 0, book_T3: 0, commonMat_Talent_T1: 6, commonMat_Talent_T2: 0, commonMat_Talent_T3: 0, worldBossMat: 0, crown: 0, mora: 12500},
      {book_T1: 0, book_T2: 2, book_T3: 0, commonMat_Talent_T1: 0, commonMat_Talent_T2: 3, commonMat_Talent_T3: 0, worldBossMat: 0, crown: 0, mora: 17500},
      {book_T1: 0, book_T2: 4, book_T3: 0, commonMat_Talent_T1: 0, commonMat_Talent_T2: 4, commonMat_Talent_T3: 0, worldBossMat: 0, crown: 0, mora: 25000},
      {book_T1: 0, book_T2: 6, book_T3: 0, commonMat_Talent_T1: 0, commonMat_Talent_T2: 6, commonMat_Talent_T3: 0, worldBossMat: 0, crown: 0, mora: 30000},
      {book_T1: 0, book_T2: 9, book_T3: 0, commonMat_Talent_T1: 0, commonMat_Talent_T2: 9, commonMat_Talent_T3: 0, worldBossMat: 0, crown: 0, mora: 37500},
      {book_T1: 0, book_T2: 0, book_T3: 4, commonMat_Talent_T1: 0, commonMat_Talent_T2: 0, commonMat_Talent_T3: 4, worldBossMat: 1, crown: 0, mora: 120000},
      {book_T1: 0, book_T2: 0, book_T3: 6, commonMat_Talent_T1: 0, commonMat_Talent_T2: 0, commonMat_Talent_T3: 6, worldBossMat: 1, crown: 0, mora: 260000},
      {book_T1: 0, book_T2: 0, book_T3: 12, commonMat_Talent_T1: 0, commonMat_Talent_T2: 0, commonMat_Talent_T3: 9, worldBossMat: 2, crown: 0, mora: 450000},
      {book_T1: 0, book_T2: 0, book_T3: 16, commonMat_Talent_T1: 0, commonMat_Talent_T2: 0, commonMat_Talent_T3: 12, worldBossMat: 2, crown: 1, mora: 700000}
    ], 
    xpMaterials: {
      character: {name: 'Hero’s Wit', amount: 20000}
    }, 
    materialList: C,
    summaryData: []
  },
  mutations: {
    increaseCount(state) {
      state.count++; 
    }, 
    updateSummaryData(state, summary) {
      if(!state.summaryData.some(data => data.id === summary.id)) {
        state.summaryData.push({id: summary.id, data: summary.data}); 
      }
      else {
        state.summaryData.find(data => { return data.id === summary.id; }).data = summary.data; 
      }
    }
  },
  actions: {
  },
  modules: {
  }
})
